NewsSource & NewsItem base class setup [Work in progress]
RocketChat/Apps.News-Aggregation pull request #6
Opened 2024-06-01 12:20 UTC by umangutkarsh

The following tasks are opened in this PR

- [ ] Initialize the base class for NewsSource
- [ ] Initialize TechCrunchNewsSource class
- [ ] Define the the NewsItem{} class to store news in a specific format
- [ ] Develop the slash command to get news updates on demand (just doing console.log() for now)

Issues with this approach
1. Typescript circular dependency issue when deploying the app

Links related to the issue - 
1. https://stackoverflow.com/questions/43176006/typeerror-class-extends-value-undefined-is-not-a-function-or-null
2. https://stackoverflow.com/questions/37312197/node-js-v6-2-0-class-extends-is-not-a-function-error/37312355#37312355

2024-06-02 09:26 UTC, abhinavkrin requested changes

2024-06-02 09:26 UTC, abhinavkrin commented on news-aggregation/news-sources/TechCrunchNewsSource.ts
> +}
This part should be removed. And the `NewsSource` class from `news-aggregation/definitions/NewsSource.ts` should be used.

2024-06-02 11:38 UTC, abhinavkrin commented
Hey @umangutkarsh 
We can take an alternative approach to avoid the issue you have mentioned,

We can have a single class NewsSource and then have adapter objects for different sources.

For example.
We can have a TechCrunchAdapter 
then initialise a new NewsSource using
```
const newsSource = new NewsSource(new TechCrunchAdapter(...));
or
const newsSource = new NewsSource(TechCrunchAdapter.create(...));
```

2024-06-03 06:18 UTC, umangutkarsh commented
> Hey @umangutkarsh We can take an alternative approach to avoid the issue you have mentioned,
> 
> We can have a single class NewsSource and then have adapter objects for different sources.
> 
> For example. We can have a TechCrunchAdapter then initialise a new NewsSource using
> 
> ```
> const newsSource = new NewsSource(new TechCrunchAdapter(...));
> or
> const newsSource = new NewsSource(TechCrunchAdapter.create(...));
> ```

Sure, will create a PR using this. Thanks.

2024-06-03 06:35 UTC, umangutkarsh commented
Hi @abhinavkrin . Please review the approach once.

2024-06-05 09:16 UTC, abhinavkrin approved these changes
LGTM! I will approve this PR. I would suggest to use `types` instead of ` any `wherever possible.

2024-06-05 09:16 UTC, merged

2024-06-05 17:58 UTC, umangutkarsh commented
> LGTM! I will approve this PR. I would suggest to use `types` instead of `any`wherever possible.

Sure, will make the changes wherever required.